server: ENC[AES256_GCM,data:ic2wg4mP/j0jRAw9MnikfgZySq7bX3ABSkWfiXToOpU=,iv:ewpTqr7wvky/wdBJJny7up2Pk2XdIuqrq9t3K+9FyUI=,tag:0/iQwrtB+HhQ6Vdx2iAGlA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3YTd4RzYvOXN0U09NMmtI
        L0VDZDRMQk9FZnlhYkpwdUJtUndsVDM3d3hVClYya3lGeXRWU09yOWNlbXV4Tm1z
        ejdnT1NCRmIxdDR1UFlPV2VQcGhPOHMKLS0tIERIeXdoZURhK1lDTmVLdG5qd0hn
        cHdlQmRSeFI2OHhlWGROUEFGNTM0VkUKPGhvM8a2GeJxNcy8H4gB1cvYDFqVicY+
        u/T747R37eyw5ykA7pXs8l49JvZQuddgv1sGdhwuOVPSOvg0w+je1A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age198xuk8yt5aqywee4zg7968ecq0ve8shhumq6fytxq5qyyp5mqvtssy66z0
  lastmodified: "2026-06-24T13:25:10Z"
  mac: ENC[AES256_GCM,data:YgAZ6NtR9KoIPLR4JhMb6/653cKnZ1SccjIEjb6hu7MSfOg5vqpy7jsvGaPBB85YFSRl9vXnOwsir+DjxS44ylbfLPGYsDLe+mzEhpqtF8AXbrnCgdLJPdIOSioGmuYLMabLws5s9Zj4XD0Q3eIk/WxVfbA87+fBkMXoWA28K+U=,iv:+JyymYUaFDkH5G7ZfVpL+K0h59WicpF1pD8QjDCocLo=,tag:qrf0RY8EvnbDZDBbseyamg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
